app/views/member_views.py
from flask import (Blueprint, request,
                   render_template, jsonify,
                   redirect, url_for, abort,
                   session
                   )
from app.database.models import User
from datetime import datetime
from app.lib.decorators import login_required
from app.lib.token import generate_token, confirm_token
from app.lib.mail import send_email
import pytz
from app import user_manager
from app.lib.user_manager import ClientType
member_blueprint = Blueprint('member', __name__, template_folder='templates')

TIME_ZONE = pytz.timezone('Asia/Taipei')
# %%


# %%


@member_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        """
        Handles the user login process.
        """
        username = request.form['username']
        password = request.form['password']

        # perform authentication logic
        user = User.query.filter_by(username=username).first()

        if user is None:
            abort(400, description=f"username {username} doesn't exist")

        if not user.is_authenticated:
            abort(400, description='account is not activated yet')

        result = user.check_password(password)
        if not result:
            abort(400, description='password is not correct.')

        # After successful login, check the 'next' parameter
        next_url = request.form.get('next', url_for('main.home'))

        # Attempt to log in the user
        user_manager.login(user.id)
        print(f'Successfully logged in. {user}')

        # [Todo] if user registered before
        # but not verified，send mail agail.

        return redirect(next_url, code=302)

    elif request.method == 'GET':

        if user_manager.user_type == ClientType.VISITOR:
            return render_template('member/login.html')
        elif user_manager.user_type == ClientType.UNVERIFIED_MEMBER:
            return redirect(url_for('member.inactive'), code=302)
        else:
            return redirect(url_for('main.home'), code=302)


@member_blueprint.route('/logout')
def logout():
    user_manager.logout()
    return redirect(url_for('member.login'), code=302)


@member_blueprint.route('/confirm_email/<token>')
def confirm_email(token):
    """
    Handles the email confirmation process using the provided token
    """
    error_msg = 'The confirmation link is invalid or has expired.'

    if user_manager.user_type == ClientType.VERIFIED_MEMBER:
        print(f'{user_manager.user} already confirmed.')
        return redirect(url_for('main.home'))

    email = confirm_token(token)
    user = User.query.filter_by(email=user_manager.user.email).first_or_404()

    if user.email == email:
        user.is_authenticated = True
        user.authenticated_time = datetime.now(TIME_ZONE)
        user.save()
        print(f'{user} confirmed the account')
        return redirect(url_for('main.home'))

    print(error_msg)
    return jsonify(error_msg)

# %%
# register function


def handle_registration():
    """
    Handles the user registration process, including checking for existing users,
    creating a new user, sending a verification email, and logging in the user.
    """
    username = request.form['username']
    password = request.form['password']
    email = request.form['email']

    check_existing_user(username, email)

    user = create_user(email, password, username)

    send_verification_email(user)
    user_manager.login(user.id)


def check_existing_user(username, email):
    """
    Checks if a user with the given username or email already exists in the database.
    """
    if User.query.filter_by(email=email).first():
        abort(409, description='該信箱已經被註冊，請改用其他信箱~')
    if User.query.filter_by(username=username).first():
        abort(409, description='該使用者名稱已經被註冊，請改用其他名稱~')


def create_user(email, password, username):
    """
    Creates a new user with the provided email, password, and username.
    """

    user = User(email=email, password=password, username=username)
    flag, msg = user.save()
    if not flag:
        print(msg)
        abort(500, description='註冊失敗，請通知網站維護人員~')
    return User.query.filter_by(email=email).first()


def send_verification_email(user):
    """
    Sends a verification email to the provided user.
    """
    token = generate_token(user.email)
    confirm_url = url_for('member.confirm_email', token=token, _external=True)
    html = render_template('member/confirm_email.html',
                           confirm_url=confirm_url)
    subject = 'Please confirm your email'
    send_email(user.email, subject, html)


@member_blueprint.route('/register', methods=('GET', 'POST'))
def register():
    """
    Handles user registration
    """
    if request.method == 'POST':

        handle_registration()
        return redirect(url_for('member.inactive'))

    return render_template('member/register.html', code=302)

# %%


@member_blueprint.route('/inactive')
@login_required
def inactive():
    """
    Renders the 'inactive' page for unverified members.
    """
    if user_manager.user_type == ClientType.VERIFIED_MEMBER:
        return redirect(url_for('main.home'))

    return render_template('member/inactive.html',
                           username=user_manager.user.username)


@member_blueprint.route('/resend')
@login_required
def resend_confirmation():
    """
    Resends the email confirmation to the current user.
    """

    if user_manager.user_type == ClientType.VERIFIED_MEMBER:
        return redirect(url_for('main.home'))

    token = generate_token(user_manager.user.email)
    confirm_url = url_for('member.confirm_email',
                          token=token, _external=True)
    html = render_template('member/confirm_email.html',
                           confirm_url=confirm_url)
    subject = 'Please confirm your email'
    send_email(user_manager.user.email, subject, html)
    return redirect(url_for('member.inactive'))

app/templates/member/confirm_email.html
<p>
  歡迎！感謝申請縮短網址服務的會員，請點選下面連結以完成驗證程序 ~
</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br />

app/templates/member/inactive.html
<head>
    <link type="text/css" rel="stylesheet" href={{ url_for('static', filename='common.css' )}}>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</head>

<body>
    <nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
        <a class="navbar-brand" href="#">IP TRACER</a>
    </nav>
    <div class="text-center">
        <h1>嗨 {{ username }} </h1>
        <br />
        <p>
            您尚未確認您的帳戶。請檢查您的收件匣（以及您的垃圾郵件資料夾） - 您應該已收到一封帶有確認連結的電子郵件。
        </p>
        <p>
            沒有收到信件嗎？
            <a href="{{ url_for('member.resend_confirmation') }}">重新發送驗證信</a>.
        </p>
    </div>
</body>

app/templates/member/login.html
<html>

<head>
  <!-- Material Design Bootstrap -->
  <link type="text/css" rel="stylesheet" href={{ url_for('static', filename='common.css' )}}>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<style>
  .container {
    min-height: 80vh;
    flex-direction: column;
  }

  .footer {
    margin-top: auto;
    background-color: #f8f9fa;
    padding: 10px;
  }

  #login-column {
    background-color: #f5f5f0;
  }

  #login-form {
    padding: 15px;
  }
</style>

<body>
  <nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#">IP TRACER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-3"
      aria-controls="navbarSupportedContent-3" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-3">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="/">首頁
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">我的收藏
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <h3 class="text-center text-white pt-5">登入表單</h3>
    <div id="login-row" class="row justify-content-center align-items-center">
      <div id="login-column" class="col-md-6">
        <form id="login-form" class="form" action="/login" method="post">
          <h3 class="text-center text-info">會員登入</h3>
          <div class="form-group">
            <label for="username" class="text-info">使用者名稱:</label><br>
            <input type="text" name="username" id="username" class="form-control">
          </div>
          <div class="form-group">
            <label for="password" class="text-info">密碼:</label><br>
            <input type="password" name="password" id="password" class="form-control">
          </div>
          <div class="form-group row" style="margin-top:25px;">
            <div class="col-sm-4">
              <input id="submit" type="submit" name="submit" class="btn btn-info" value="送出">
            </div>
            <div class="col-sm-8 text-right">還不是會員嗎？
              <a href="/register" class="text-info">申請帳號</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

<script type=text/javascript>
 $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
 SUCCESS = "success"
 FAIL = "fail"
 const urlParams = new URLSearchParams(window.location.search);
 const nextParam = urlParams.get('next');
 console.log(nextParam)

 $(document).ready(function () {

  function switchLoadingStatus(status) {
        if (status == "start") {
            $("#submit").prop('disabled', true)
            $("#submit").val("登入中...")
        }
        else if (status == "end") {
            $("#submit").prop('disabled', false)
            $("#submit").val("送出")
        }
    }

    $('#login-form').submit(async function (event) {

      event.preventDefault();
     
      switchLoadingStatus("start")

      const formData =  {
        username: $('input[name="username"]').val(),
        password: $('input[name="password"]').val(),
        next:nextParam
      }

      let result = validateInputFormat(formData)
      if (!result[0]){
        Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: result[1],
            })
        switchLoadingStatus("end")
        return 
      }
    
      const action = $('#login-form').attr('action')

      try {
        result = await axios.post(action, formData, {headers: {'Content-Type': 'multipart/form-data'}})
        window.location.href = result.request.responseURL;
      } catch (error) {
        Swal.fire({
              icon: 'error',
              title: error.response.data.error,
              text: error.response.data.message
          })
      } finally{
        switchLoadingStatus("end")
      }
    });

    function validateInputFormat(formdata){
      console.log("validateInputFormat")
      if (formdata["username"] === ""){
        return [false,"使用者帳號不能為空 ~"]
      }
      if (formdata["password"] === ""){
        return [false,"使用者密碼不能為空 ~"]
      }
      return [true]
    }

});
</script>

</html>

app/templates/member/register.html
<html>

<head>
  <!-- Material Design Bootstrap -->
  <link type="text/css" rel="stylesheet" href={{ url_for('static', filename='common.css' )}}>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<style>
  #login-column {
    background-color: #f5f5f0;
  }

  #login-form {
    padding: 15px;
  }
</style>

<body>
  <nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#">IP TRACER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-3"
      aria-controls="navbarSupportedContent-3" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-3">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="/">首頁
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link">我的收藏
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div id="register">
    <h3 class="text-center text-white pt-5">登入表單</h3>
    <div class="container">
      <div id="login-row" class="row justify-content-center align-items-center">
        <div id="login-column" class="col-md-6">
          <form id="login-form" class="form" action="/register" method="post">
            <h3 class="text-center text-info">會員申請</h3>
            <div class="form-group">
              <label for="username" class="text-info">電子信箱:</label><br>
              <input type="text" name="email" placeholder="可收信的驗證信箱" id="email" class="form-control">
            </div>
            <div class="form-group">
              <label for="username" class="text-info">使用者名稱:</label><br>
              <input type="text" name="username" placeholder="限英文字母、數字 6-12碼" id="username" class="form-control">
            </div>
            <div class="form-group">
              <label for="password" class="text-info">密碼:</label><br>
              <input type="password" name="password" placeholder="限英文字母、數字及*!@# 8-12碼" id="password"
                class="form-control">
            </div>
            <div class="form-group">
              <label for="password" class="text-info">密碼確認:</label><br>
              <input type="password" name="password2" placeholder="限英文字母、數字及*!@# 8-12碼" id="password2"
                class="form-control">
            </div>
            <div class="form-group row" style="margin-top:25px;">
              <div class="col-sm-4">
                <input id="submit" type="submit" name="submit" class="btn btn-info btn-md" value="送出">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>

<script type=text/javascript>
 $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};

 const validateEmail = (email) => {
      return String(email)
        .toLowerCase()
        .match(
          /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
        );
    };
 $(document).ready(function () {

  function validateInputFormat(formdata){
      console.log("validateInputFormat")

      if (!validateEmail(formdata["email"])){
        return [false,"電子信箱格式有誤~"]
      }

      if (formdata["username"].length <6 ||formdata["username"].length > 12  ){
        return [false,"使用者名稱長度必須介於 6 ~ 12"]
      }

      if (formdata["password"].length <8 ||formdata["password"].length >12 ){
        return [false,"使用者密碼長度必須介於 8 ~ 12"]
      }

      if (formdata["password"]!=formdata["password2"]){
        return [false,"密碼與確認密碼不一致"]
      }

      return [true]
    }

  function switchLoadingStatus(status) {
        // switch component of form before and after submiting
        console.log("switchLoadingStatus")
        if (status == "start") {

            $("#email").prop('disabled', true)
            $("#username").prop('disabled', true)
            $("#password").prop('disabled', true)
            $("#password2").prop('disabled', true)
            $("#submit").prop('disabled', true)
            $("#submit").val("申請中...")

        }
        else if (status == "end") {

            $("#email").prop('disabled', false)
            $("#username").prop('disabled', false)
            $("#password").prop('disabled', false)
            $("#password2").prop('disabled', false)
            $("#submit").prop('disabled', false)
            $("#submit").val("送出")

        }
    }

    $('#login-form').submit(async function (event) {

      // check formdata
      event.preventDefault();
      switchLoadingStatus("start")

      const formData =  {
        email: $('input[name="email"]').val(),
        username: $('input[name="username"]').val(),
        password: $('input[name="password"]').val(),
        password2: $('input[name="password2"]').val()
      }

      let result = validateInputFormat(formData)
      if (!result[0]){
        Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: result[1],
            })
        switchLoadingStatus("end")
        return 
      }

      // submit form
      const action = $('#login-form').attr('action')
      try {

        response = await axios.post(action, formData, {headers: {'Content-Type': 'multipart/form-data'} })
        const redirectUrl = response.request.responseURL;

        Swal.fire({
          text: `已寄出驗證連結至 ${formData.email}，請收信以完成申請流程噢 ~`,
          icon: 'success'

        }).then((result) => {
          // Check if the user clicked "OK"
          if (result.isConfirmed) {
              window.location.href = redirectUrl;
          }
        });
      } catch (error) {

        // Handle error
        console.log(error)
        Swal.fire({
            icon: 'error',
            title: error.response.data.error,
            text: error.response.data.message
          })

      } finally{

        switchLoadingStatus("end")

      }
      
  
    });

   

});
</script>

</html>